import "./styles.css";
import { defineAppShell } from "./shell/app-shell";
import { defineTopNav } from "./components/top-nav";
import { defineFeedItem } from "./components/feed-item";
import { defineMdEditor } from "./components/md-editor";
import { defineHomeView } from "./views/home-view";
import { defineCreateView } from "./views/create-view";
import { definePaintCanvas } from "./components/paint-canvas";
import { definePaintView } from "./views/paint-view";
import { defineAccountView } from "./views/account-view";
import { defineWallScroll } from "./components/wall-scroll";

defineTopNav();
defineFeedItem();
defineMdEditor();
defineWallScroll();
defineHomeView();
defineCreateView();
definePaintCanvas();
definePaintView();
defineAccountView();
defineAppShell();
